services:
  pg:
    image: postgres:15
    container_name: pg
    # restart: unless-stopped
    environment:
      # default user: postgres
      POSTGRES_PASSWORD: s2u2m1234
    ports:
      - "5432:5432"
    volumes:
      - ./pg/volumes:/var/lib/postgresql/data
